name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore .\MockUp\ChangeRequest.csproj

      - name: Build
        run: dotnet build .\MockUp\ChangeRequest.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test .\MockUp\ChangeRequest.csproj --configuration Release --no-build
